### ISSUE TITLE
icnet and dfanet error

### ISSUE THREAD

**Issue by pawopawo** [LikeLy-Journey/SegmenTron#19]
```
Traceback (most recent call last):
  File "./tools/train.py", line 224, in <module>
    trainer.train()
  File "./tools/train.py", line 166, in train
    self.validation(epoch)
  File "./tools/train.py", line 198, in validation
    self.metric.update(output, target)
  File "/SegmenTron/segmentron/utils/score.py", line 58, in update
    evaluate_worker(self, preds, labels)
  File "/SegmenTron/segmentron/utils/score.py", line 41, in evaluate_worker
    correct, labeled = batch_pix_accuracy(pred, label)
  File "/SegmenTron/segmentron/utils/score.py", line 93, in batch_pix_accuracy
    pixel_correct = torch.sum((predict == target) * (target > 0))#.item()
RuntimeError: The size of tensor a (2040) must match the size of tensor b (2048) at non-singleton dimension 2
```
when I run `./tools/dist_train.sh configs/cityscapes_icnet_resnet.yaml 4`, the above error was generated during validation

**Comment by pawopawo** [comment]
```
Traceback (most recent call last):
  File "./tools/train.py", line 224, in <module>
    trainer.train()
  File "./tools/train.py", line 136, in train
    outputs = self.model(images)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 376, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/SegmenTron/segmentron/models/dfanet.py", line 53, in forward
    stage2_enc2 = self.enc2_2(torch.cat([stage1_enc2, stage1_out], dim=1))
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 196 and 193 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71
```

when I run `./tools/dist_train.sh configs/cityscapes_dfanet.yaml 4`, the above error was generated

**Comment by LikeLy-Journey** [comment]
thanks for report this bug. I will fix it soon.
