### ISSUE TITLE
tainning voc dataset error

### ISSUE THREAD

**Issue by yangweixiang** [LikeLy-Journey/SegmenTron#39]
conda create --name pointrend python=3.6

conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch

CUDA_VISIBLE_DEVICES=2 python -u tools/train.py --config-file configs/pascal_voc_deeplabv3_plus.yaml

[THOP Defined] Conv2d
[THOP Defined] BatchNorm2d
[THOP Defined] ReLU
[THOP Defined] Conv2d
[THOP Defined] BatchNorm2d
[THOP Defined] ReLU
[THOP Defined] Conv2d
[THOP Defined] BatchNorm2d
[THOP Defined] ReLU
[THOP Defined] Conv2d
[THOP Defined] BatchNorm2d
[THOP Defined] ReLU
[THOP Defined] Conv2d
<class 'torch.Tensor'>
2020-04-10 15:14:51,053 Segmentron WARNING: get flops and params error: new() received an invalid combination of arguments - got (list, dtype=torch.dtype), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: dtype

2020-04-10 15:14:51,054 Segmentron INFO: Not use SyncBatchNorm!
2020-04-10 15:14:51,054 Segmentron INFO: Set bn custom eps for bn in encoder: 0.001
2020-04-10 15:14:51,060 Segmentron INFO: Start training, Total Epochs: 50 = Total Iterations 9150
<class 'torch.Tensor'>
Traceback (most recent call last):
  File "tools/train.py", line 221, in <module>
    trainer.train()
  File "tools/train.py", line 133, in train
    outputs = self.model(images)
  File "/home/yangwx/anaconda2/envs/pointrend/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/data2/yangwx/GIT/SegmenTron/segmentron/models/deeplabv3_plus.py", line 36, in forward
    c1, _, c3, c4 = self.encoder(x)
  File "/home/yangwx/anaconda2/envs/pointrend/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/data2/yangwx/GIT/SegmenTron/segmentron/models/backbones/xception.py", line 131, in forward
    x = self.conv1(x)
  File "/home/yangwx/anaconda2/envs/pointrend/lib/python3.6/site-packages/torch/nn/modules/module.py", line 495, in __call__
    hook_result = hook(self, input, result)
  File "/home/yangwx/anaconda2/envs/pointrend/lib/python3.6/site-packages/thop/vision/basic_hooks.py", line 27, in count_convNd
    m.total_ops += torch.DoubleTensor([int(total_ops)], dtype=torch.float64)
TypeError: new() received an invalid combination of arguments - got (list, dtype=torch.dtype), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: dtype

**Comment by LikeLy-Journey** [comment]
You can try to comment these lines: https://github.com/LikeLy-Journey/SegmenTron/blob/master/tools/train.py#L65-L69
