### ISSUE TITLE
Do you have match-table of network and backbone??

### ISSUE THREAD

**Issue by edwardcho** [LikeLy-Journey/SegmenTron#41]
Hello Sir,

I was tested your code using my data (image resolution : 256).
But I could not train many cases.

![image](https://user-images.githubusercontent.com/29569662/79408673-dd416200-7fd6-11ea-87c5-2a1f7da1db7c.png)

If you don't mind, please tell me trainable networks and matched backbone.

Thanks.

**Comment by edwardcho** [comment]
Hello Sir,

In many cases,
I got some error.

2020-04-16 02:49:10,095 Segmentron WARNING: get flops and params error: Given groups=1, weight of size 128 512 1 1, expected input[1, 2048, 1, 1] to have 512 channels, but got 2048 channels instead
2020-04-16 02:49:10,096 Segmentron INFO: Not use SyncBatchNorm!
2020-04-16 02:49:10,098 Segmentron INFO: Start training, Total Epochs: 1 = Total Iterations 367
Traceback (most recent call last):
  File "tools/train.py", line 332, in <module>
    trainer.train()
  File "tools/train.py", line 135, in train
    outputs = self.model(images)
  File "/home/itsme/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/TESTBOARD/additional_networks/segmentation/semantic_segmentation_likelyjourney_pytorch_modify/segmentron/models/bisenet.py", line 36, in forward
    spatial_out = self.spatial_path(x)
  File "/home/itsme/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/TESTBOARD/additional_networks/segmentation/semantic_segmentation_likelyjourney_pytorch_modify/segmentron/models/bisenet.py", line 81, in forward
    x = self.conv7x7(x)
  File "/home/itsme/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/TESTBOARD/additional_networks/segmentation/semantic_segmentation_likelyjourney_pytorch_modify/segmentron/modules/basic.py", line 75, in forward
    x = self.bn(x)
  File "/home/itsme/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 549, in __call__
    hook_result = hook(self, input, result)
  File "/home/itsme/anaconda3/lib/python3.7/site-packages/thop/vision/basic_hooks.py", line 49, in count_bn
    m.total_ops += torch.DoubleTensor([int(total_ops)])
UnboundLocalError: local variable 'total_ops' referenced before assignment

I wonder what is the problems??

Thanks.
